version: '3.8'
services:
  mysql-container:
    image: mysql:8.4
    container_name: mysql-container
    volumes:
      - mysql-data:/var/lib/mysql
  java-container:
    build: .
    container_name: java-container
    stdin_open: true
    tty: true
    depends_on:
      - mysql-container
volumes:
  mysql-data: